services:
  matic:
    build: .
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
    command: rabbitmq-server
    expose:
      - "5672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 2s
      timeout: 10s
      retries: 5
